#
# Generates helper code for converting a list of component types into
# runtime-iterable arrays and and if-statement lists for use in lookup 
# functions.
# 
# Usage:
# ComponentList_generate(
#     components/@list.h      # in
#     components/all.h.in     # template
#     components/all.h        # out
# )
#
# Given the above, ... 
# Looks for component enum in @list.h in the form of:
#
# enum class Components {
#     Info = 1,
#     Mesh = 3,
# };
#
# Note that:
# • The order they appear in the list will be preserved in the array order.
# • Each item must have an explicit value assigned.
# • The enum value is intended to never change and safe for serialization. 
# • The enum values (IDs) do not necessarily need to be sequential.
#
# From that enum, it generates a list of component types and their ids, 
# and populates all.h.in with CMAKE variables as follows:
#
# ComponentList_message                     # Warning "do not edit" comment.
# ComponentList_includes                    # Include list of all components.
# ComponentList_enum                        # Regenerated enum to repeat in output.
# ComponentList_typeCount                   # Number of components found.
# ComponentList_typeListAsStrings           # List of componets as quoted strings
# ComponentList_fnComponentId               # If statements, check var "name", returns id
# ComponentList_fnComponentIndex            # If statements, check var "name", returns index
# ComponentList_fnEmplaceComponentByName    # If statements, checks var "name", runs r.emplace<Type>(e)
# ComponentList_fnEmplaceComponentByIndex   # If statements, checks var "index", runs r.emplace<Type>(e)
# ComponentList_fnEmplaceComponentById      # If statements, checks var "id", runs r.emplace<Type>(e)
# 
# Writes result to all.h
#


function(ComponentList_generate infile templatefile outfile)
    # read file, find the enum, match the contents between {}
    file(READ ${infile} whole_file)
    string(REGEX MATCH "enum[ \t\r\n]+class[ \t\r\n]+Components[ \t\r\n]*{([^}]*)}" _ ${whole_file})

    # test to make sure we found contents in the enum
    if(NOT CMAKE_MATCH_1)
        message(FATAL_ERROR "Could not find Components enum")
        return()
    endif()

    # strip ALL whitespace
    string(REGEX REPLACE "[ \t\r\n]" "" items ${CMAKE_MATCH_1})
    # convert to list
    string(REPLACE "," ";" items ${items})
    
    # look at the contents and generate list of types and ids
    set(type_id_pairs)
    foreach(item ${items})
        # skip if empty
        if(item STREQUAL "")
            continue()
        endif()
        # match the "Type = 1" sequence
        string(REGEX MATCH "([A-Za-z_]+[A-Za-z0-9_]*)=([0-9]+)" _ ${item})
        # show warning if matches are not found at all
        if(NOT CMAKE_MATCH_1 OR NOT CMAKE_MATCH_2)
            message(WARNING "Error parsing component in Components enum (${item})")
            continue()
        endif()
        list(APPEND type_id_pairs "${CMAKE_MATCH_1},${CMAKE_MATCH_2}")
    endforeach()

    # SET VARIABLES TO BE USED IN configure_file TEMPLATE

    string(APPEND ComponentList_message
        "//\n"
        "// Generated by CMAKE. DO NOT EDIT.\n"
        "// Edit Components enum in ${infile}\n"
        "//\n"
    )

    list(LENGTH type_id_pairs ComponentList_typeCount)

    set(count 0)
    foreach(item ${type_id_pairs})
        string(REPLACE "," ";" item ${item})
        list(GET item 0 type)
        list(GET item 1 id)
        set(if_name "if (strcmp(name, \"${type}\") == 0)")
        set(if_index "if (index == ${count})")
        set(if_id "if (id == ${id})")
        set(endl   "\n    ")

        string(APPEND ComponentList_includes
            "#include \"${type}.h\"\n"
        )

        string(APPEND ComponentList_typeListAsStrings
            "\"${type}\",${endl}"
        )

        string(APPEND ComponentList_enum
            "${type} = ${id},${endl}"
        )

        string(APPEND ComponentList_fnComponentId
            "${if_name} return ${id};${endl}"
        )

        string(APPEND ComponentList_fnComponentIndex
            "${if_name} return ${count};${endl}"
        )

        string(APPEND ComponentList_fnEmplaceComponentByName
            "${if_name} r.emplace<${type}>(e);${endl}"
        )

        string(APPEND ComponentList_fnEmplaceComponentByIndex
            "${if_index} r.emplace<${type}>(e);${endl}"
        )

        string(APPEND ComponentList_fnEmplaceComponentById
            "${if_id} r.emplace<${type}>(e);${endl}"
        )

        math(EXPR count "${count} + 1")
    endforeach()

    set(ComponentList_enum "enum class Components {\n    ${ComponentList_enum}\n};\n")

    configure_file(
        "${CMAKE_CURRENT_SOURCE_DIR}/${templatefile}"
        "${CMAKE_CURRENT_SOURCE_DIR}/${outfile}"
    )

    add_custom_target(
        ComponentList_target
        DEPENDS ${outfile}
    )
endfunction()